name: mock_web_server
version: 2.0.0
description: Web server that can be used for testing HTTP clients
author: Miguel Castiblanco <miguel@starcarr.co>
homepage: https://gitlab.com/Starcarr/MockWebServer

dev_dependencies:
  test: "0.12.24+2"
  resource: ">=2.1.2 <3.0.0"