name: mock_web_server
version: 1.0.0
description: Web server that can be used for testing HTTP clients
author: Miguel Castiblanco <miguel@starcarr.co>
homepage: https://gitlab.com/Starcarr/MockWebServer

dev_dependencies:
  test: "0.12.24+2"